/* eslint-disable @typescript-eslint/naming-convention */
const BACKGROUND_CHARACTER = '.';
const FACE_1_CHARACTER = '@';
const FACE_2_CHARACTER = '$';
const FACE_3_CHARACTER = '~';
const FACE_4_CHARACTER = '#';
const FACE_5_CHARACTER = ';';
const FACE_6_CHARACTER = '+';

const BACKGROUND_CHARACTER_COLOR = 'rgba(0, 0, 0, 1)';
const FACE_1_CHARACTER_COLOR = 'rgba(255, 0, 0, 1)';
const FACE_2_CHARACTER_COLOR = 'rgba(0, 255, 0, 1)';
const FACE_3_CHARACTER_COLOR = 'rgba(0, 0, 255, 1)';
const FACE_4_CHARACTER_COLOR = 'rgba(255, 255, 0, 1)';
const FACE_5_CHARACTER_COLOR = 'rgba(255, 0, 255, 1)';
const FACE_6_CHARACTER_COLOR = 'rgba(0, 255, 255, 1)';

const MIN_ROTATION_SPEED = -0.05;
const MAX_ROTATION_SPEED = 0.05;

export {
	BACKGROUND_CHARACTER,
	FACE_1_CHARACTER,
	FACE_2_CHARACTER,
	FACE_3_CHARACTER,
	FACE_4_CHARACTER,
	FACE_5_CHARACTER,
	FACE_6_CHARACTER,
	BACKGROUND_CHARACTER_COLOR,
	FACE_1_CHARACTER_COLOR,
	FACE_2_CHARACTER_COLOR,
	FACE_3_CHARACTER_COLOR,
	FACE_4_CHARACTER_COLOR,
	FACE_5_CHARACTER_COLOR,
	FACE_6_CHARACTER_COLOR,
	MIN_ROTATION_SPEED,
	MAX_ROTATION_SPEED,
};
