/* eslint-disable @typescript-eslint/naming-convention */
const BACKGROUND_CHARACTER = '.';
const FACE_1_CHARACTER = '@';
const FACE_2_CHARACTER = '$';
const FACE_3_CHARACTER = '~';
const FACE_4_CHARACTER = '#';
const FACE_5_CHARACTER = ';';
const FACE_6_CHARACTER = '+';

const MIN_ROTATION_SPEED = -0.08;
const MAX_ROTATION_SPEED = 0.08;

export {
	BACKGROUND_CHARACTER,
	FACE_1_CHARACTER,
	FACE_2_CHARACTER,
	FACE_3_CHARACTER,
	FACE_4_CHARACTER,
	FACE_5_CHARACTER,
	FACE_6_CHARACTER,
	MIN_ROTATION_SPEED,
	MAX_ROTATION_SPEED,
};
